// GENERATED by distill/extract_html_semantics.js — DO NOT EDIT. Regenerate deliberately.
//
// Sources, each stamped with its publication date and a hash of what was read:
//   https://html.spec.whatwg.org/multipage/rendering.html  (2 September 2026, a8a3759c8f80e9fd)
//   https://w3c.github.io/aria/  (2026-08-29, 06801e0dc89a000f)
//   https://w3c.github.io/html-aam/  (2026-07-29, a564cfeaed7719d6)
//
// UA_RULES: the user-agent stylesheet's rules carrying a consumed property, in source order, each
// with its selector list and declarations ({prop, value, important}). ARIA_STATES: the aria-*
// attributes the ARIA spec classes as states. NATIVE_STATES: HTML attributes whose unconditional
// HTML-AAM mapping is one of those states ({attribute, elements, state, value}).

export const UA_RULES = [
	{
		"selectors": [
			"area",
			"base",
			"basefont",
			"datalist",
			"head",
			"link",
			"meta",
			"noembed",
			"noframes",
			"param",
			"rp",
			"script",
			"style",
			"template",
			"title"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "none",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"[hidden]:not([hidden=until-found i]):not(embed)"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "none",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"[hidden=until-found i]:not(embed)"
		],
		"declarations": [
			{
				"prop": "content-visibility",
				"value": "hidden",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"embed[hidden]"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "inline",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"input[type=hidden i]"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "none",
				"important": true
			}
		]
	},
	{
		"selectors": [
			"noscript"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "none",
				"important": true
			}
		]
	},
	{
		"selectors": [
			"html",
			"body"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"address",
			"blockquote",
			"center",
			"dialog",
			"div",
			"figure",
			"figcaption",
			"footer",
			"form",
			"header",
			"hr",
			"legend",
			"listing",
			"main",
			"p",
			"plaintext",
			"pre",
			"search",
			"xmp"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"address"
		],
		"declarations": [
			{
				"prop": "font-style",
				"value": "italic",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"listing",
			"plaintext",
			"pre",
			"xmp"
		],
		"declarations": [
			{
				"prop": "font-family",
				"value": "monospace",
				"important": false
			},
			{
				"prop": "white-space",
				"value": "pre",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"dialog:not([open])"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "none",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"dialog::backdrop"
		],
		"declarations": [
			{
				"prop": "background",
				"value": "rgba(0,0,0,0.1)",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"[popover]:not(:popover-open):not(dialog[open])"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "none",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"dialog:popover-open"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"slot"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "contents",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"pre[wrap]"
		],
		"declarations": [
			{
				"prop": "white-space",
				"value": "pre-wrap",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"cite",
			"dfn",
			"em",
			"i",
			"var"
		],
		"declarations": [
			{
				"prop": "font-style",
				"value": "italic",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"b",
			"strong"
		],
		"declarations": [
			{
				"prop": "font-weight",
				"value": "bolder",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"code",
			"kbd",
			"samp",
			"tt"
		],
		"declarations": [
			{
				"prop": "font-family",
				"value": "monospace",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"sub"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "sub",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"sup"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "super",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"ruby"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "ruby",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"rt"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "ruby-text",
				"important": false
			}
		]
	},
	{
		"selectors": [
			":link",
			":visited"
		],
		"declarations": [
			{
				"prop": "text-decoration",
				"value": "underline",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"mark"
		],
		"declarations": [
			{
				"prop": "background",
				"value": "yellow",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"abbr[title]",
			"acronym[title]"
		],
		"declarations": [
			{
				"prop": "text-decoration",
				"value": "dotted underline",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"ins",
			"u"
		],
		"declarations": [
			{
				"prop": "text-decoration",
				"value": "underline",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"del",
			"s",
			"strike"
		],
		"declarations": [
			{
				"prop": "text-decoration",
				"value": "line-through",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"q::before"
		],
		"declarations": [
			{
				"prop": "content",
				"value": "open-quote",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"q::after"
		],
		"declarations": [
			{
				"prop": "content",
				"value": "close-quote",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"nobr"
		],
		"declarations": [
			{
				"prop": "white-space",
				"value": "nowrap",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"nobr wbr"
		],
		"declarations": [
			{
				"prop": "white-space",
				"value": "normal",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"article",
			"aside",
			":heading",
			"hgroup",
			"nav",
			"section"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			":heading"
		],
		"declarations": [
			{
				"prop": "font-weight",
				"value": "bold",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"dir",
			"dd",
			"dl",
			"dt",
			"menu",
			"ol",
			"ul"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"li"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "list-item",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"table"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "table",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"caption"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "table-caption",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"colgroup",
			"colgroup[hidden]"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "table-column-group",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"col",
			"col[hidden]"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "table-column",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"thead",
			"thead[hidden]"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "table-header-group",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"tbody",
			"tbody[hidden]"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "table-row-group",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"tfoot",
			"tfoot[hidden]"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "table-footer-group",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"tr",
			"tr[hidden]"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "table-row",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"td",
			"th"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "table-cell",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"colgroup[hidden]",
			"col[hidden]",
			"thead[hidden]",
			"tbody[hidden]",
			"tfoot[hidden]",
			"tr[hidden]"
		],
		"declarations": [
			{
				"prop": "visibility",
				"value": "collapse",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"th"
		],
		"declarations": [
			{
				"prop": "font-weight",
				"value": "bold",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"thead",
			"tbody",
			"tfoot",
			"table > tr"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "middle",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"tr",
			"td",
			"th"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "inherit",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"thead[valign=top i]",
			"tbody[valign=top i]",
			"tfoot[valign=top i]",
			"tr[valign=top i]",
			"td[valign=top i]",
			"th[valign=top i]"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "top",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"thead[valign=middle i]",
			"tbody[valign=middle i]",
			"tfoot[valign=middle i]",
			"tr[valign=middle i]",
			"td[valign=middle i]",
			"th[valign=middle i]"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "middle",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"thead[valign=bottom i]",
			"tbody[valign=bottom i]",
			"tfoot[valign=bottom i]",
			"tr[valign=bottom i]",
			"td[valign=bottom i]",
			"th[valign=bottom i]"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "bottom",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"thead[valign=baseline i]",
			"tbody[valign=baseline i]",
			"tfoot[valign=baseline i]",
			"tr[valign=baseline i]",
			"td[valign=baseline i]",
			"th[valign=baseline i]"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "baseline",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"td[nowrap]",
			"th[nowrap]"
		],
		"declarations": [
			{
				"prop": "white-space",
				"value": "nowrap",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"table"
		],
		"declarations": [
			{
				"prop": "font-weight",
				"value": "initial",
				"important": false
			},
			{
				"prop": "font-style",
				"value": "initial",
				"important": false
			},
			{
				"prop": "white-space",
				"value": "initial",
				"important": false
			}
		]
	},
	{
		"selectors": [
			":is(table, thead, tbody, tfoot, tr) > form"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "none",
				"important": true
			}
		]
	},
	{
		"selectors": [
			"input",
			"button"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "inline-block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"textarea"
		],
		"declarations": [
			{
				"prop": "white-space",
				"value": "pre-wrap",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"fieldset"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"embed[align=top i]",
			"iframe[align=top i]",
			"img[align=top i]",
			"input[type=image i][align=top i]",
			"object[align=top i]"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "top",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"embed[align=baseline i]",
			"iframe[align=baseline i]",
			"img[align=baseline i]",
			"input[type=image i][align=baseline i]",
			"object[align=baseline i]"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "baseline",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"embed[align=texttop i]",
			"iframe[align=texttop i]",
			"img[align=texttop i]",
			"input[type=image i][align=texttop i]",
			"object[align=texttop i]"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "text-top",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"embed[align=absmiddle i]",
			"iframe[align=absmiddle i]",
			"img[align=absmiddle i]",
			"input[type=image i][align=absmiddle i]",
			"object[align=absmiddle i]",
			"embed[align=abscenter i]",
			"iframe[align=abscenter i]",
			"img[align=abscenter i]",
			"input[type=image i][align=abscenter i]",
			"object[align=abscenter i]"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "middle",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"embed[align=bottom i]",
			"iframe[align=bottom i]",
			"img[align=bottom i]",
			"input[type=image i][align=bottom i]",
			"object[align=bottom i]"
		],
		"declarations": [
			{
				"prop": "vertical-align",
				"value": "bottom",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"details",
			"summary"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"details > summary:first-of-type"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "list-item",
				"important": false
			}
		]
	},
	{
		"selectors": [
			":host summary"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "list-item",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"marquee"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "inline-block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"option"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"optgroup"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "block",
				"important": false
			},
			{
				"prop": "font-weight",
				"value": "bolder",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"select"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "inline-block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"select option"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "flex",
				"important": false
			},
			{
				"prop": "white-space",
				"value": "nowrap",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"select option::checkmark"
		],
		"declarations": [
			{
				"prop": "content",
				"value": "'\\2713' / ''",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"select option:not(:checked)::checkmark"
		],
		"declarations": [
			{
				"prop": "visibility",
				"value": "hidden",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"select optgroup"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "block",
				"important": false
			},
			{
				"prop": "font-weight",
				"value": "bolder",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"select optgroup option"
		],
		"declarations": [
			{
				"prop": "font-weight",
				"value": "normal",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"select"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "inline-flex",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"select > button:first-child"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "contents",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"select::picker-icon"
		],
		"declarations": [
			{
				"prop": "content",
				"value": "counter(fake-counter-name, disclosure-open)",
				"important": false
			},
			{
				"prop": "display",
				"value": "block",
				"important": false
			}
		]
	},
	{
		"selectors": [
			"select"
		],
		"declarations": [
			{
				"prop": "display",
				"value": "inline-block",
				"important": false
			}
		]
	}
];

export const ARIA_STATES = [
	"aria-busy",
	"aria-checked",
	"aria-current",
	"aria-disabled",
	"aria-expanded",
	"aria-hidden",
	"aria-invalid",
	"aria-pressed",
	"aria-selected"
];

export const NATIVE_STATES = [
	{
		"attribute": "checked",
		"elements": "input type=checkbox or type=radio",
		"state": "aria-checked",
		"value": "true"
	},
	{
		"attribute": "disabled",
		"elements": "button; input; optgroup; option; select; textarea; form-associated custom element",
		"state": "aria-disabled",
		"value": "true"
	},
	{
		"attribute": "disabled",
		"elements": "fieldset",
		"state": "aria-disabled",
		"value": "true"
	},
	{
		"attribute": "open",
		"elements": "details",
		"state": "aria-expanded",
		"value": "true"
	},
	{
		"attribute": "selected",
		"elements": "option",
		"state": "aria-selected",
		"value": "true"
	}
];
